version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - NODE_TAG=${NODE_TAG:-18.2.0-alpine3.15}
        - NGINX_TAG=${NGINX_TAG:-1.21.6-alpine}
        - PROJECT_WORKDIR=${PROJECT_WORKDIR:-/srv/app}
        - NGINX_HOST=${NGINX_HOST:-80}
        - NGINX_HTTP_PORT=${NGINX_HTTP_PORT:-csf2mlb2c.it}
    image: ${PROJECT_NAME}:${PROJECT_TAG}
    env_file:
      - .env.prod
    ports:
      # HTTP
      - target: ${NGINX_HTTP_PORT:-80}
        published: ${ANGULAR_PORT:-4400}
        protocol: tcp
